# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xlive/cpp/ffmpegcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xlive/cpp/ffmpegcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xlive/cpp/ffmpegcpp/CMakeFiles /home/xlive/cpp/ffmpegcpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xlive/cpp/ffmpegcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testffcpp.out

# Build rule for target.
testffcpp.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testffcpp.out
.PHONY : testffcpp.out

# fast build rule for target.
testffcpp.out/fast:
	$(MAKE) -f CMakeFiles/testffcpp.out.dir/build.make CMakeFiles/testffcpp.out.dir/build
.PHONY : testffcpp.out/fast

AV.o: AV.cpp.o
.PHONY : AV.o

# target to build an object file
AV.cpp.o:
	$(MAKE) -f CMakeFiles/testffcpp.out.dir/build.make CMakeFiles/testffcpp.out.dir/AV.cpp.o
.PHONY : AV.cpp.o

AV.i: AV.cpp.i
.PHONY : AV.i

# target to preprocess a source file
AV.cpp.i:
	$(MAKE) -f CMakeFiles/testffcpp.out.dir/build.make CMakeFiles/testffcpp.out.dir/AV.cpp.i
.PHONY : AV.cpp.i

AV.s: AV.cpp.s
.PHONY : AV.s

# target to generate assembly for a file
AV.cpp.s:
	$(MAKE) -f CMakeFiles/testffcpp.out.dir/build.make CMakeFiles/testffcpp.out.dir/AV.cpp.s
.PHONY : AV.cpp.s

log.o: log.cpp.o
.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) -f CMakeFiles/testffcpp.out.dir/build.make CMakeFiles/testffcpp.out.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i
.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) -f CMakeFiles/testffcpp.out.dir/build.make CMakeFiles/testffcpp.out.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s
.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) -f CMakeFiles/testffcpp.out.dir/build.make CMakeFiles/testffcpp.out.dir/log.cpp.s
.PHONY : log.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/testffcpp.out.dir/build.make CMakeFiles/testffcpp.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/testffcpp.out.dir/build.make CMakeFiles/testffcpp.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/testffcpp.out.dir/build.make CMakeFiles/testffcpp.out.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... testffcpp.out"
	@echo "... AV.o"
	@echo "... AV.i"
	@echo "... AV.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

